# -*- coding: utf-8 -*-
"""simple_pytorch_ann.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cWgHkJ_LD-grpYG0-EeDxIXLJhQqIuXS
"""



"""Simple PyTorch ANN"""

import torch
import torch.nn as nn

model = nn.Sequential(
    nn.Linear(2, 4),
    nn.ReLU(),
    nn.Linear(4, 1)
)

X = torch.tensor([[0.,0.],[0.,1.],[1.,0.],[1.,1.]])
y = torch.tensor([[0.],[1.],[1.],[0.]])

"""### **4.Loss Function and Optimizer**

MSELoss measures prediction error.

Asam optimizer updates weights efficiently.
"""

loss_fn = nn.MSELoss()
opt = torch.optim.Adam(model.parameters(), lr=0.01)

"""### **5.Training Loop**"""

for _ in range(1000):
    opt.zero_grad()
    loss = loss_fn(model(X), y)
    loss.backward()
    opt.step()

"""### **6. Model Inference**"""

print(model(X))